version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ml_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentiment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ml_api
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: ml_mysql
      MYSQL_DATABASE: sentiment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    depends_on:
      - mysql
    volumes:
      - ./api:/app

volumes:
  mysql_data:
