version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ml_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentiment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/migrations:/docker-entrypoint-initdb.d/migrations
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/sample-data.sql:/docker-entrypoint-initdb.d/sample-data.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 0s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ml_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  minio:
    image: minio/minio
    container_name: ml_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ml_api
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: ml_mysql
      MYSQL_DATABASE: sentiment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MINIO_ENDPOINT_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_REGION_NAME: us-east-1
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./api:/app
    
  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml_ml
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      DB_HOST: ml_mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: sentiment_db
      MINIO_ENDPOINT_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_REGION_NAME: us-east-1
    volumes:
      - ./ml:/app

volumes:
  mysql_data:
  minio_data: